version: "3.9"
services: 
  wallsfunhd:
    command: npm run dev
    container_name: wallsfunhd
    ports: 
      - '3000:3000'
    build:
      context: .
      dockerfile: Dockerfile
    volumes: 
      - ./:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/.next